# Generated by Django 2.1.4 on 2018-12-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Импульсный свет', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.FileField(upload_to=''),
        ),
    ]
